services:
  db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: stockapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5437:5432"

  app:
    build: .
    container_name: stock-api
    ports:
      - "8080:8080"
    environment:
      - DATASOURCE_URL=jdbc:postgresql://db:5432/stockapi
      - DATASOURCE_USERNAME=postgres
      - DATASOURCE_PASSWORD=postgres
      - GOOGLE_CLIENT_ID=${GOOGLE_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_SECRET}
      - SPRING_PROFILES_ACTIVE=production
    depends_on:
      - db